const resources = {
  en: {
    translation: {
      calendar: "Calendar",
      staff: "Staff",
      wage: "Wage",
      settings: "Settings",
      id: "ID",
      password: "Password",
      login: "Login",
      loginWithGoogle: "Login with Google",
      notuser: "Create an account and start STAFull",
      signup: "Sign Up",
      userInfo: "User Info",
      storeInfo: "Store Info",
      usedId: "ID already in use",
      notMatchPw: "Passwords do not match",
      typeyourpw: "Enter your password",
      typeyourpw2: "Re-enter your password",
      storeName: "Store Name",
      ownerName: "Owner's Name",
      openingDate: "Opening Date",
      loginLine: "Staff in Your Hands",
      checkId: "Check Availability",
      pwValidationText:
        "Password must be 8-20 characters, including 1 uppercase letter and 1 special symbol",
      idValidationText:
        "ID must be 4-20 characters long and can include numbers",
      nameValidationText: "Numbers and special symbols cannot be included",
      storeNameValidationText: "Special symbols cannot be included",
      sunday: "Sunday",
      monday: "Monday",
      tuesday: "Tuesday",
      wendsday: "Wendsday",
      thursday: "Thursday",
      friday: "Friday",
      saturday: "Saturday",
      todayStaff: "Today's Staff",
      nextShift: "Next Shift",
    },
  },
  kr: {
    translation: {
      calendar: "달력",
      staff: "직원",
      wage: "급여",
      settings: "설정",
      id: "아이디",
      password: "비밀번호",
      login: "로그인",
      loginWithGoogle: "구글로 로그인",
      notuser: "아직 회원이 아니신가요?",
      signup: "가입하기",
      userInfo: "기본정보",
      storeInfo: "매장정보",
      usedId: "이미 사용 중인 아이디입니다",
      notMatchPw: "비밀번호가 일치하지 않습니다",
      typeyourpw: "비밀번호를 입력하세요",
      typeyourpw2: "비밀번호를 다시 입력하세요",
      storeName: "매장명",
      ownerName: "사장님 이름",
      openingDate: "개업일",
      loginLine: "간단한 직원관리",
      checkId: "중복체크",
      pwValidationText:
        "비밀번호는 대문자 1개와 특수 기호 1개를 포함해 8자 이상 20자 이하여야 합니다.",
      idValidationText:
        "아이디는 4자 이상 20자 이하의 영문 대소문자와 숫자만 허용됩니다",
      nameValidationText: "숫자와 특수 기호는 포함될 수 없습니다",
      storeNameValidationText: "특수기호는 포함될 수 없습니다.",
      sunday: "일요일",
      monday: "월요일",
      tuesday: "화요일",
      wendsday: "수요일",
      thursday: "목요일",
      friday: "금요일",
      saturday: "토요일",
      todayStaff: "오늘 근무자",
      nextShift: "다음 근무표",
    },
  },
};

export default resources;
